version: "2"
volumes:
  data-db:
  payments:
services:
  paymentsdb:
    image: mongo
    restart: always
    volumes:
      - 'data-db:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: payments_db
    ports:
      - 27017:27017

  paymentsms:
    build: .
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - 'payments:/payments_proj'
    ports:
      - 8000:8000
    links:
      - paymentsdb
    depends_on:
      - migration

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - 'payments:/payments_proj'
    links:
      - paymentsdb
    depends_on:
      - makemigrations

  makemigrations:
    build: .
    image: app
    command: 'python manage.py makemigrations'
    volumes:
      - 'payments:/payments_proj'
    links:
      - paymentsdb
    depends_on:
      - paymentsdb
